spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Date序列化格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_ENUMS_USING_INDEX: true

  #404 抛异常
  mvc:
    throw-exception-if-no-handler-found: true
    date-format: yyyy-MM-dd HH:mm:ss

  resources:
    add-mappings: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  servlet:
    session:
      cookie:
        #客户端可以获取cookie
        http-only: false

logging:
  level:
    # log request info
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.muyun.springboot.mybatis.LogMapper: DEBUG

#  devtools:
#    restart:
#      additional-exclude:




