spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot
    username: root
    password: root



#  devtools:
#    restart:
#      additional-exclude:
