spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #Date序列化格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



#  devtools:
#    restart:
#      additional-exclude:
